---
name: Build Bazzite images
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build_push:
    strategy:
      fail-fast: false
      matrix:
        base_image:
          - bazzite-dx-gnome
        tag:
          - stable
          - testing
    uses: ./.github/workflows/build-image.yml
    with:
      base_image: ${{ matrix.base_image }}
      tag: ${{ matrix.tag }}
      image_desc: "Bazzite with MediaTek MT7927/MT6639 WiFi 7 and Bluetooth kernel module patches"
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
